version: "3"

services: 
  api:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:  
      - .:/usr/app
  db:
    image: postgres:latest 
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432' 
